version: '3'
services:
  bench:
    build:
      context: ./bench
    depends_on:
      - web
    networks:
      - frontend
  web:
    build:
      context: ./web
    volumes:
      - ./web/log:/var/log/nginx/
      - ./webapp/img:/home/isucon/isubata/webapp/public/icons
    networks:
      - frontend
      - backend
    depends_on:
      - app
    ports:
      - "80:80"
  app:
    build:
      context: ./webapp
    volumes:
      - ./webapp/go/src:/home/isucon/isubata/webapp/go/src
      - ./webapp/img:/home/isucon/isubata/webapp/img
      - ./webapp/img_init:/home/isucon/isubata/webapp/img_init
    ports:
      - "5000"
    networks:
      - backend
    depends_on:
      - db
    environment:
      ISUBATA_DB_USER: isucon
      ISUBATA_DB_PASSWORD: isucon
      ISUBATA_DB_HOST: db
  db:
    build:
      context: ./db
    volumes:
      - ./db/log:/var/log/mysql
    ports:
      - "3306"
    networks:
      - backend
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
networks:
  frontend:
  backend:
